In [1]:
import sqlite3 as sql
import pandas as pd

In [2]:
con = sql.connect('iot.db')

In [3]:
pd.read_sql_query('select * from iot_measurements',con)

,keyname,ts,sub_ts,olcum_degeri
0,FrontPress3_Motor_Vibration.ab-1,2021-02-02T00:59:49.371Z,0,0.434028
1,FrontPress3_Motor_Vibration.ab-1,2021-02-02T00:59:49.371Z,101,0.438549
2,FrontPress3_Motor_Vibration.ab-1,2021-02-02T00:59:49.371Z,201,0.434028
3,FrontPress3_Motor_Vibration.ab-1,2021-02-02T00:59:49.371Z,301,0.434028
4,FrontPress3_Motor_Vibration.ab-1,2021-02-02T00:59:49.371Z,402,0.432219
...,...,...,...,...
3816,RearPress2_Motor_Temperature,2021-02-02T01:00:00.155Z,5001,33.299999
3817,RearPress2_Motor_Temperature,2021-02-02T01:00:00.155Z,6001,33.299999
3818,RearPress2_Motor_Temperature,2021-02-02T01:00:00.155Z,7002,33.299999
3819,RearPress2_Motor_Temperature,2021-02-02T01:00:00.155Z,8002,33.299999
3820,RearPress2_Motor_Temperature,2021-02-02T01:00:00.155Z,9002,33.299999

In [15]:
pd.read_sql_query('select * from iot_measurements where keyname = "FrontPress3_Motor_Vibration.ab-2" order by olcum_degeri desc limit 10' ,con)

,keyname,ts,sub_ts,olcum_degeri
0,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:49.678Z,4005,0.550673
1,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:59.685Z,1000,0.548864
2,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:59.685Z,6004,0.548864
3,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:49.678Z,2005,0.545247
4,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:49.678Z,9006,0.545247
5,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:59.685Z,8005,0.543439
6,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:59.685Z,4003,0.528971
7,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:49.678Z,6006,0.527163
8,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:49.678Z,0,0.525354
9,FrontPress3_Motor_Vibration.ab-2,2021-02-02T00:59:49.678Z,7006,0.525354

In [19]:
pd.read_sql_query('select ts,sub_ts from iot_measurements where ts like "%1Z" and sub_ts like "4%" limit 8 ',con)

                         ts  sub_ts
0  2021-02-02T00:59:49.371Z     402
1  2021-02-02T00:59:49.371Z    4011
2  2021-02-02T00:59:49.371Z    4112
3  2021-02-02T00:59:49.371Z    4212
4  2021-02-02T00:59:49.371Z    4312
5  2021-02-02T00:59:49.371Z    4412
6  2021-02-02T00:59:49.371Z    4512
7  2021-02-02T00:59:49.371Z    4612